version: '3.8'

services:
  education-bot:
    build: .
    container_name: education-bot
    restart: unless-stopped
    ports:
      - "10000:10000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=10000
    env_file:
      - .env
    volumes:
      - ./temp:/app/temp
      - ./libruary:/app/libruary:ro  # Read-only access to PDF library
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a simple monitoring service
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300  # Check for updates every 5 minutes
    profiles:
      - monitoring

networks:
  default:
    driver: bridge
